### ISSUE TITLE
Revise User Stories Based on Use Case Diagrams

### ISSUE THREAD

**Issue by lkekana** [COS301-SE-2024/TuneIn#17]
from demo 1 doc:

## User stories/ user characteristics 
List all intended users and explain for what purpose each would use the system.

**Comment by lkekana** [comment]
also from client, add:
- acceptance criteria
    - minimal functionality for user story to be compete
    - what it takes to make feature
- new name for user 5, condense user groups: casual, enthusiast, curator

**Comment by NerinaBorchard** [comment]
documentation/User characteristics and stories v3.pdf
