### ISSUE TITLE
Make quality requirements

### ISSUE THREAD

**Issue by lkekana** [COS301-SE-2024/TuneIn#32]
From demo 1 doc: _"Specify and quantify each of the system’s quality requirements. Examples of quality requirements include performance, reliability, scalability, security maintainability, and usability. This will be revised and extended for demo 2."_

**Comment by lkekana** [comment]
@u22528492 re-opening this so you can send the link before closing. please also do that for other docs so it's easier to keep track of

**Comment by lkekana** [comment]
also, i think a couple more QRs should be added (did some research from various projects and mixed in explanations from Chat with my own)

for Performance
while the QRs address response time and throughput, i think we need a mention of resource utilization.
- Resource Utilization: Define acceptable limits for CPU, memory, and network usage to ensure efficient operation.

for Security,
i think we should add:
- Authorization: Ensure proper user roles and permissions are defined and enforced.
- Auditing and Logging: Implement comprehensive logging and monitoring for security events, ensuring logs are tamper-proof and reviewed regularly.

for Usability Requirements,
- Internationalisation and Localization: Support for multiple languages and regional settings to cater to a global audience (as per the last part of FRs)

for Maintainability,
- Modularity: Design the system in interchangeable modules to facilitate easier updates and maintenance. (lots of 214 stuff)
- Code Readability: Ensure code is well-documented and follows a consistent style for ease of understanding (also add that there will be code documentation in Typedoc, using appropriate comment blocks)
- Ease of Updates and Patches: Establish procedures for deploying updates and patches without significant downtime (basically builds will be on github and won't disturb the frontend but also add a strategy for ensuring we don't have hectic downtime while deploying new code from github onto AWS for backend & API)

also add Portability,
- Platform Compatibility: Ensure the application can run on multiple operating systems and platforms. (our app being Native for Android and iOS using Flutter and as a PWA)
- Interoperability: Define how the system integrates with other systems or services (OAuth, streaming service integration, etc - see FRs)
- Software Dependencies: Manage and document software dependencies to avoid conflicts and ensure smooth deployment across different environments (discuss how we can best track dependencies)

and for Reliability:
- Fault Tolerance: Ensure the system can handle component failures without complete system failure (i think you can discuss the Component-Based Architecture - see Linda's discussion of this in his doc on discord) 
- Recovery Time: Specify the maximum acceptable time to recover from failures (your discretion)
- Backup and Restore Procedures: Ensure regular backups and a clear restore process are in place (a base strategy for this would help a lot)

**Comment by u22528492** [comment]
Final QR doc: https://docs.google.com/document/d/1HA9cM_GOdNC7_sUcTyf3_IuY3L1H81YqXYUcA0EHtWQ/edit
