### ISSUE TITLE
Create Use Case Diagrams

### ISSUE THREAD

**Issue by lkekana** [COS301-SE-2024/TuneIn#5]
from demo 1 doc:
_"Draw high-level use case diagrams for your system’s use cases. Number them for traceability purposes. Ensure use cases are done using a service contract approach, as this will greatly assist in designing tests for your system. https://www.visual-paradigm.com/guide/umlunified-modeling-language/what-is-use-case-diagram/ "_

**Comment by lkekana** [comment]
Also add estimates for user groups.

Advice from Chat:
### Estimations in Use Case Diagrams
Estimations provide a way to assess the effort, time, and resources needed for each use case. This helps in project planning and resource allocation. Estimations can include:

1. **Effort Estimation**
   - Time: "This use case is estimated to take 20 hours of development."
   - Complexity: "This use case has a complexity level of 3 out of 5."

2. **Resource Estimation**
   - Personnel: "This use case requires 2 developers and 1 QA engineer."
   - Tools: "This use case requires access to the payment gateway API."

**Comment by lkekana** [comment]
@u22528492 also re-opening this for the same reason as https://github.com/COS301-SE-2024/TuneIn/issues/32, you can either link to the doc or the issue should only be closed after a PR to dev (once the relevant files are on the repo)

**Comment by u22528492** [comment]
Final QR doc: https://docs.google.com/document/d/1HA9cM_GOdNC7_sUcTyf3_IuY3L1H81YqXYUcA0EHtWQ/edit

**Comment by u22528492** [comment]
Wrong one

**Comment by u22528492** [comment]
Final use case diagrams: https://github.com/COS301-SE-2024/TuneIn/blob/documentation/documentation/UseCases.drawio
