### ISSUE TITLE
Create UML Class Diagram

### ISSUE THREAD

**Issue by lkekana** [COS301-SE-2024/TuneIn#8]
from demo 1 doc:

## Class Diagram 
Illustrate the software solution using a valid and correctly formatted UML class diagram. Ensure correct use of association, aggregation, composition and related concepts such as multiplicity.

**Comment by lkekana** [comment]
Remember to highlight classes, their relationships, class functions, and interactions.

**Comment by thabisomatau** [comment]
class diagram documentation has been completed alongside design patterns documentation for demo 1.
